export default {
  FETCH_REQUEST: 'app/FETCH_REQUEST',
  FETCH_SUCCESS: 'app/FETCH_SUCCESS',
  FETCH_FAILURE: 'app/FETCH_FAILURE',

  GET_DARK_MODE: 'app/GET_DARK_MODE',
  SET_DARK_MODE: 'app/SET_DARK_MODE'
};
