export default {
  GET_DARK_MODE: 'app/GET_DARK_MODE',
  SET_DARK_MODE: 'app/SET_DARK_MODE',

  GET_USER_SUBSCRIPTION: 'app/GET_USER_SUBSCRIPTION',
  SET_USER_SUBSCRIPTION: 'app/SET_USER_SUBSCRIPTION',

  FETCH_POPULAR_VIDEOS: 'app/FETCH_POPULAR_VIDEOS',
  FETCH_SUCCESS_POPULAR_VIDEOS: 'app/FETCH_SUCCESS_POPULAR_VIDEOS',
  FETCH_FAILURE_POPULAR_VIDEOS: 'app/FETCH_FAILURE_POPULAR_VIDEOS'
};
