export default {
  GET_DARK_MODE: 'app/GET_DARK_MODE',
  SET_DARK_MODE: 'app/SET_DARK_MODE',

  FETCH_POPULAR_VIDEOS: 'app/FETCH_POPULAR_VIDEOS',

  FETCH_SUCCESS: 'app/FETCH_SUCCESS',
  FETCH_FAILURE: 'app/FETCH_FAILURE'
};
